[package]
name = "mcu-traits"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
defmt = { version = "1.0", optional = true }

[features]
default = ["defmt"]
defmt = ["dep:defmt"]

